site_name: Stab
site_desc: 'Stab: Start Blogging w/ Simple static blog generator'
site_baseurl: /stab

author: oxalorg
plugins:
    - highlight # Provides fenced_code_blocks with pygments code highlighting

# Default values
# Can be removed from the config file
layout: post # can be overwritten on an individual basis
plugins_dir: _plugins
blog_dir: blog
